void-linux/void-linux.github.io

_posts/2018-11-05-forum-is-down.markdown
=> Fix stackexchange link

assets/js/voidsearch.js
=> voidsearch: do not change packages.name in showPackages

_config.yml
I've disabled snow effect, since Christmas is over. This should also update the copyright notice(?) since it still says 2019
=> Disabled snow

index.html
* Add PowerPC to the architecture list
* Fix punctuation
* Change "compiling" to "compiled"
=> Home page: fix the introductory text

index.html
Initial PR for discussion, further to [this comment](https://github.com/void-linux/void-linux.github.io/pull/85#discussion_r399016601) by @the-maldridge.
=> Home: Make Twitter, IRC and build.voidlinux.org links more explicit.

_posts/2020-04-24-some-context.markdown
By request of @the-maldridge, a screenshot of xtraeme's [Twitter bio](https://twitter.com/xtraemeat) is attached.
=> Spelling/grammar cleanup, fix pronouns referring to xtraeme

_layouts/default.html
=> Fix link to xtraeme

index.html
This PR is accompanied by https://github.com/void-linux/void-docs/pull/349. Suggestions for better wording/phrasing welcome. :-)
=> /index.html: Mention focus on stability, not bleeding-edge.

README, _layouts/default.html, atom.xml, index.html
=> Use https where possible

download/index.markdown
Add note about porting the wiki pages.
=> download: update ARM information.

_posts/2020-12-11-pam-1.5.1.markdown
When this is merged, I'll pin the same text on Reddit for maximum attention.
=> _posts: add notice about pam_tally breakage in pending pam upgrade

_config.yml, index.html
It can be an accessibility issue.
=> Disable christmas mode.

download/index.markdown
Better language, better logic, better link text. ;)
=> Download page: Improve paragraph on image verification

download/index.markdown
Just added "or tarball" to the first sentence.
=> download: Mention tarballs also in verification section

assets/css/misc.css, assets/js/voidsearch.js, packages/index.markdown
=> Add package search exact match feature

_posts/2021-05-21-libera.markdown, index.html
=> index.html: move to libera for IRC.

assets/js/voidsearch.js
I like to add custom search engines to my browser (vivaldi) for easy site-specific searches. Currently the package search on the void website ignores the url query string that get filled in when adding the package search as a search engine (see images below).
My changes allow for adding the package search as a search engine by running the query given in the query string if a valid architecture is given.
=> add package search on load if url parameters exist

assets/js/voidsearch.js
=> add message when there are no results in package search

_posts/2021-09-23-hacktoberfest.markdown
I copy/pasted a lot of the guide section from last year.  We could maybe add something about ethereal chroot to get people to run the tests, but in many ways I feel like just having them run CI on their forks is probably the better option.
=> Add post for hacktoberfest 2021

_config.yml
It's now christmas time, so it's time to show it on the website.
I haven't enabled snow because of #125 where there were accessibility issues for some people.
=> Enabled christmas mode

acknowledgments/index.md
Cf. void-linux/void-infrastructure#149
=> acknowledgements: Add 23M to acknowledgement's page

_config.yml
It is once again this time of the year.
=> Enable Christmas mode

_posts/2023-02-09-log-service-change.markdown
for void-linux/void-packages#42026
=> _posts: add post about logging change

_posts/2023-05-30-audio-breakage.md
requires void-linux/void-packages#44141 and void-linux/void-docs#759
=> blog post for breaking changes in audio

_posts/2023-07-09-new-images.md
draft for now, until images are signed
=> _posts: add post for 20230628 images

_posts/2023-10-07-python3-external.md
cc @ahesford
for reference:
- void-linux/void-packages#43703
- void-linux/void-packages#43735
=> _posts: add post about python3 external change

_config.yml, _posts/2024-03-14-new-images.md
https://devspace.voidlinux.org/abby/live/void-live-20240314/
=> _posts: add 20240314 image announcement
