void-linux/void-linux.github.io

- index.html
It doesn't break the link for right now it as still redirects to the .eu
> Update some links to use the new ".org"

- _layouts/default.html
- assets/css/misc.css
- assets/js/voidsearch.js
- packages/index.markdown
This replaces the package search with a primitive one through xq-api.
Due to a limitation of the API, the architecture list is a drop-down
instead of being presented in the table -- so, users have to
unfortunately know which architecture they want to search.
The architectures list is populated by the API, so if a new one is
added (e.g., PowerPC), then it should be picked up automatically with
an xq-api reload.
This also moves the jquery and bootstrap scripts into the page head.
There's a chance this could slow down page rendering a bit, but without
the ability to add scripts to the end of the body after jquery, the
voidsearch.js and others can't make use of jquery reliably. So, a small
hit that shouldn't be noticable after caching seems better than writing
a bunch of code to work around …
> packages: Rewrite search to use xq-api

- _posts/2019-01-23-dhcpcd-7.1.0.markdown
review: @Duncaen 
grammar: @the-maldridge @Vaelatern
> NEWS: dhcpcd>=7.1.0 update may require manual intervention

- download/index.markdown
This is a PR to add Lysator's FTP as a void-linux mirror.
> download: add lysator acs mirror

- _layouts/default.html
Removes the Wiki from the Navigation, adds Documentation instead (to docs.voidlinux.org)
The wiki isn't maintained anymore and has plain wrong information in it, the "Post Installation" site especially is nothing I'd want a new user to consume.
Even with information missing from docs, I think too sparse documentation is better than wrong.
Another point is that new registrations for the wiki aren't possible anymore.
> site: docs instead of wiki in navigation

- atom.xml
This just makes it so people can read the news posts in whatever program they're using to fetch the feed.
> Add post content to Atom feed

- _layouts/default.html
- contribute/index.markdown
The PR seeks to make it easier for people to find CONTRIBUTING and the "Contributing > Void Docs" section of the Handbook, with the intent of (hopefully) reducing the number of PRs which don't follow project guidelines.
> Add 'Contribute' page.

- download/index.markdown
* Separate into more sub headers
* Use more consistent formatting (lists and code blocks)
* Still link to the wiki because there isn't a replacement docs page,
but be explicit about deprecation
* Remove mirrors
Partially fixes #88 
@the-maldridge Regarding the removal of the mirrors listed there, are there any that still have to be moved to https://docs.voidlinux.org/xbps/repositories/mirrors/index.html ? (I'm asking you because you are listed as the contact for mirrors).
> Downloads: update and make more explicit

- download/index.markdown
Needs to wait for https://github.com/void-linux/void-docs/pull/233, but would make the docs the go-to place for everything. Currently, the linked PR has removed GPG verification. Should we keep it?
> Downloads: refer to the docs for verification

- _layouts/default.html
RSS is a different feed type, voidlinux.org is using Atom feed
> Correct feed type

- _config.yml
> Deprecation: The 'gems' configuration option has been renamed to 'plugins'. Please update your config file accordingly.
> Fix deprecation warning

- _layouts/default.html
Closes #86 
I'm not in love with this change, because it requires, at a minimum, changing the header in void-docs and in the man.voidlinux.org (ironically enough), if we want to keep everything consistent.
> _layouts/default: add Manual Pages link.

- assets/css/misc.css
- packages/index.markdown
I added some Bootstrap classes to package search form to make it look more consistent.
> Packages search - tweak form style

- Gemfile.lock
- _layouts/default.html
- acknowledgments/index.md
This PR adds an acknowledgements page that thanks those who sponsor the hardware that comprises the Void fleet.
@leahneukirchen, @bougyman, @Gottox please verify that you appear in this file as you wish to be represented.
@void-linux/webmasters for patch review and approval.
> Add acknowledgments page

- _posts/2020-10-01-hacktoberfest.markdown
In light of digitalocean/hacktoberfest#596 this patch adds information that we can no longer promise contributions will count to the hacktoberfest challenge.
My personal stance is that we should pull out of the challenge entirely and this update should reflect that.   The sponsoring organization changed the rules mid-run without warning and is very clumsily implementing an opt-in mechanism that games the github search algorithm to pop their event to the top.  This should have been a filter on their side, not something that required maintainers to spam their topics across github.
It is in the best interest that this be published as soon as possible so that contributors have up to date information when searching projects to contribute to, but it must be reviewed adequately.
> Update information on hacktoberfest

- acknowledgments/index.md
This adds acknowledgement for pulux hosting b-lej-de, but this host is down and I'd ideally like them to review this PR before I merge it to add their consulting company if they have one or otherwise make sure it looks right.
> acknowledgements: Add pulux

- _config.yml
- _includes/download_arm.html
- _includes/download_details_pc.md
- _includes/download_pc.html
- _includes/download_sbc.html
- _layouts/default.html
- _layouts/download.html
- _platforms/arm.md
- _platforms/i686.md
- _platforms/sbc.md
- _platforms/x86_64.md
- assets/css/misc.css
- assets/js/tabbar.js
- download/index.markdown
I have spent some time on  adding download links to the "Download" page and I'm curious what everyone think about this version:
| x86 | i686 | arm | nojs |
| ----- | ----- | --- | --- |
|  ![Screenshot_2020-10-06 Enter the void - Downloads](https://user-images.githubusercontent.com/673861/95148235-516afe80-07df-11eb-8c9f-fa8da1d4ca93.png)  |  ![Screenshot_2020-10-06 Enter the void - Downloads(1)](https://user-images.githubusercontent.com/673861/95148247-5b8cfd00-07df-11eb-8a25-0dc5aa396d60.png)  |  ![Screenshot_2020-10-06 Enter the void - Downloads(2)](https://user-images.githubusercontent.com/673861/95148256-621b7480-07df-11eb-9e45-05474789f2ba.png) | ![Screenshot_2020-10-06 Enter the void - Downloads(3)](https://user-images.githubusercontent.com/673861/95148270-68115580-07df-11eb-8a55-b3 …
> Add download links to the download page

- _posts/2020-05-01-new-contributors.markdown
https://voidlinux.org/contribute/ has been removed.
Fixes #121.
> 2020-05-01-new-contributors: point "Contribute Page" to docs.voidlinux.

- _layouts/default.html
Applications with feed discovery use this name for the feed's title.
This change gives a better automatic name for the feed on feed readers.
> Use a non-generic name for the atom feed

- _layouts/default.html
- assets/css/screen.css
At about 900px width navbar breaks into two lines. It was hovering page
content on /download and /acknowledgments . Use dedicated css in place
of older technique of fixed margin. On older browsers navbar scrolls
together with page.
Demo at <https://chocimier.github.io/void-linux.github.io/download/>
Hovering titles on voidlinux.org is not a big deal, but it is at http://54.37.137.89/pkgs.void , searchbox is completely hidden.
> Adjust navbar to not hover page main content

- _config.yml
- _posts/2018-11-12-new-images.markdown
- _posts/2020-10-01-hacktoberfest.markdown
- _posts/2021-09-23-hacktoberfest.markdown
sets the downloads page to point to repo-default, and updates links in a few news posts to prevent link-rot
> various: replace alpha.de links with repo-default

- _platforms/sbc.md
for void-linux/void-packages#39442
> _platforms/sbc.md: update rpi image names, remove dead links

- _includes/download_pc.html
- _platforms/i686.md
- _platforms/x86_64.md
due to void-linux/void-mklive#275, the base image now has a consistent suffix, allowing for simplified logic in the downloads page.
Don't merge this until new images are released.
> _includes/download_pc.html: simplify logic for live iso downloads

- _config.yml
_„Don't cry because it's over. Smile because it happened.“_ 
- Dr. Seuss
Sure, it's hard to let something as precious as Void Linux website christmas mode go, but sadly both Catholic and Orthodox christmases already happened and it's time to disable it again. Next year we will glimpse the beauty of it again, so don't be upset.
> Disable christmas mode

- assets/css/misc.css
This fixes the page contents going over the navbar while scrolling.
Z-index is used since that's the only solution that functions and gained consensus in #169.
Fixes #168
Closes #169 (same solution but with an absurd z-index value, and has been completely stalled)
Closes #172 (makes the navbar stick to the top of the document, not the top of the viewport)
> assets/css/misc.css: add z-index to .navbar

- _posts/2024-01-22-xbps-src-host-arch.md
for void-linux/void-packages#46263
> _posts: post about host arch flag

- Gemfile.lock
- assets/js/voidcommits.js
- index.html
closes https://github.com/void-linux/void-linux.github.io/pull/196
closes https://github.com/void-linux/void-linux.github.io/pull/201
closes https://github.com/void-linux/void-linux.github.io/pull/202
fixes https://github.com/void-linux/void-linux.github.io/issues/208
> replace twitter feed with void-packages pull feed
